[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

[dependencies]
miette.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

