[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
miette = "7.4.0"
pretty_assertions = "1.4.1"
test-log = "0.2.16"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

